/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/signUp'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PharmaciesRouteImport } from './routes/pharmacies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthblogRouteImport } from './routes/healthblog'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AboutUsRouteImport } from './routes/aboutUs'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorSlotsRouteImport } from './routes/doctor/slots'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRecordsRouteImport } from './routes/_layout/records'
import { Route as LayoutPrescriptionsRouteImport } from './routes/_layout/prescriptions'
import { Route as LayoutMessagesRouteImport } from './routes/_layout/messages'
import { Route as LayoutDoctorSlotsRouteImport } from './routes/_layout/doctorSlots'
import { Route as LayoutDoctorDashboardRouteImport } from './routes/_layout/doctorDashboard'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutBillingRouteImport } from './routes/_layout/billing'
import { Route as LayoutAppointmentsRouteImport } from './routes/_layout/appointments'

const SignUpRoute = SignUpRouteImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmaciesRoute = PharmaciesRouteImport.update({
  id: '/pharmacies',
  path: '/pharmacies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthblogRoute = HealthblogRouteImport.update({
  id: '/healthblog',
  path: '/healthblog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/aboutUs',
  path: '/aboutUs',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorSlotsRoute = DoctorSlotsRouteImport.update({
  id: '/doctor/slots',
  path: '/doctor/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutRecordsRoute = LayoutRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutPrescriptionsRoute = LayoutPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutMessagesRoute = LayoutMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDoctorSlotsRoute = LayoutDoctorSlotsRouteImport.update({
  id: '/doctorSlots',
  path: '/doctorSlots',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDoctorDashboardRoute = LayoutDoctorDashboardRouteImport.update({
  id: '/doctorDashboard',
  path: '/doctorDashboard',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutBillingRoute = LayoutBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutAppointmentsRoute = LayoutAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboutUs': typeof AboutUsRoute
  '/contacts': typeof ContactsRoute
  '/healthblog': typeof HealthblogRoute
  '/login': typeof LoginRoute
  '/pharmacies': typeof PharmaciesRoute
  '/services': typeof ServicesRoute
  '/signUp': typeof SignUpRoute
  '/appointments': typeof LayoutAppointmentsRoute
  '/billing': typeof LayoutBillingRoute
  '/chat': typeof LayoutChatRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/doctorDashboard': typeof LayoutDoctorDashboardRoute
  '/doctorSlots': typeof LayoutDoctorSlotsRoute
  '/messages': typeof LayoutMessagesRoute
  '/prescriptions': typeof LayoutPrescriptionsRoute
  '/records': typeof LayoutRecordsRoute
  '/settings': typeof LayoutSettingsRoute
  '/doctor/slots': typeof DoctorSlotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboutUs': typeof AboutUsRoute
  '/contacts': typeof ContactsRoute
  '/healthblog': typeof HealthblogRoute
  '/login': typeof LoginRoute
  '/pharmacies': typeof PharmaciesRoute
  '/services': typeof ServicesRoute
  '/signUp': typeof SignUpRoute
  '/appointments': typeof LayoutAppointmentsRoute
  '/billing': typeof LayoutBillingRoute
  '/chat': typeof LayoutChatRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/doctorDashboard': typeof LayoutDoctorDashboardRoute
  '/doctorSlots': typeof LayoutDoctorSlotsRoute
  '/messages': typeof LayoutMessagesRoute
  '/prescriptions': typeof LayoutPrescriptionsRoute
  '/records': typeof LayoutRecordsRoute
  '/settings': typeof LayoutSettingsRoute
  '/doctor/slots': typeof DoctorSlotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/aboutUs': typeof AboutUsRoute
  '/contacts': typeof ContactsRoute
  '/healthblog': typeof HealthblogRoute
  '/login': typeof LoginRoute
  '/pharmacies': typeof PharmaciesRoute
  '/services': typeof ServicesRoute
  '/signUp': typeof SignUpRoute
  '/_layout/appointments': typeof LayoutAppointmentsRoute
  '/_layout/billing': typeof LayoutBillingRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/doctorDashboard': typeof LayoutDoctorDashboardRoute
  '/_layout/doctorSlots': typeof LayoutDoctorSlotsRoute
  '/_layout/messages': typeof LayoutMessagesRoute
  '/_layout/prescriptions': typeof LayoutPrescriptionsRoute
  '/_layout/records': typeof LayoutRecordsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/doctor/slots': typeof DoctorSlotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutUs'
    | '/contacts'
    | '/healthblog'
    | '/login'
    | '/pharmacies'
    | '/services'
    | '/signUp'
    | '/appointments'
    | '/billing'
    | '/chat'
    | '/dashboard'
    | '/doctorDashboard'
    | '/doctorSlots'
    | '/messages'
    | '/prescriptions'
    | '/records'
    | '/settings'
    | '/doctor/slots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutUs'
    | '/contacts'
    | '/healthblog'
    | '/login'
    | '/pharmacies'
    | '/services'
    | '/signUp'
    | '/appointments'
    | '/billing'
    | '/chat'
    | '/dashboard'
    | '/doctorDashboard'
    | '/doctorSlots'
    | '/messages'
    | '/prescriptions'
    | '/records'
    | '/settings'
    | '/doctor/slots'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/aboutUs'
    | '/contacts'
    | '/healthblog'
    | '/login'
    | '/pharmacies'
    | '/services'
    | '/signUp'
    | '/_layout/appointments'
    | '/_layout/billing'
    | '/_layout/chat'
    | '/_layout/dashboard'
    | '/_layout/doctorDashboard'
    | '/_layout/doctorSlots'
    | '/_layout/messages'
    | '/_layout/prescriptions'
    | '/_layout/records'
    | '/_layout/settings'
    | '/doctor/slots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  ContactsRoute: typeof ContactsRoute
  HealthblogRoute: typeof HealthblogRoute
  LoginRoute: typeof LoginRoute
  PharmaciesRoute: typeof PharmaciesRoute
  ServicesRoute: typeof ServicesRoute
  SignUpRoute: typeof SignUpRoute
  DoctorSlotsRoute: typeof DoctorSlotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signUp': {
      id: '/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacies': {
      id: '/pharmacies'
      path: '/pharmacies'
      fullPath: '/pharmacies'
      preLoaderRoute: typeof PharmaciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthblog': {
      id: '/healthblog'
      path: '/healthblog'
      fullPath: '/healthblog'
      preLoaderRoute: typeof HealthblogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboutUs': {
      id: '/aboutUs'
      path: '/aboutUs'
      fullPath: '/aboutUs'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/slots': {
      id: '/doctor/slots'
      path: '/doctor/slots'
      fullPath: '/doctor/slots'
      preLoaderRoute: typeof DoctorSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/records': {
      id: '/_layout/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof LayoutRecordsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/prescriptions': {
      id: '/_layout/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof LayoutPrescriptionsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/messages': {
      id: '/_layout/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof LayoutMessagesRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/doctorSlots': {
      id: '/_layout/doctorSlots'
      path: '/doctorSlots'
      fullPath: '/doctorSlots'
      preLoaderRoute: typeof LayoutDoctorSlotsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/doctorDashboard': {
      id: '/_layout/doctorDashboard'
      path: '/doctorDashboard'
      fullPath: '/doctorDashboard'
      preLoaderRoute: typeof LayoutDoctorDashboardRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/billing': {
      id: '/_layout/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof LayoutBillingRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/appointments': {
      id: '/_layout/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof LayoutAppointmentsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutAppointmentsRoute: typeof LayoutAppointmentsRoute
  LayoutBillingRoute: typeof LayoutBillingRoute
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutDoctorDashboardRoute: typeof LayoutDoctorDashboardRoute
  LayoutDoctorSlotsRoute: typeof LayoutDoctorSlotsRoute
  LayoutMessagesRoute: typeof LayoutMessagesRoute
  LayoutPrescriptionsRoute: typeof LayoutPrescriptionsRoute
  LayoutRecordsRoute: typeof LayoutRecordsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutAppointmentsRoute: LayoutAppointmentsRoute,
  LayoutBillingRoute: LayoutBillingRoute,
  LayoutChatRoute: LayoutChatRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutDoctorDashboardRoute: LayoutDoctorDashboardRoute,
  LayoutDoctorSlotsRoute: LayoutDoctorSlotsRoute,
  LayoutMessagesRoute: LayoutMessagesRoute,
  LayoutPrescriptionsRoute: LayoutPrescriptionsRoute,
  LayoutRecordsRoute: LayoutRecordsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  ContactsRoute: ContactsRoute,
  HealthblogRoute: HealthblogRoute,
  LoginRoute: LoginRoute,
  PharmaciesRoute: PharmaciesRoute,
  ServicesRoute: ServicesRoute,
  SignUpRoute: SignUpRoute,
  DoctorSlotsRoute: DoctorSlotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
